"use client";
import { api } from "@/lib/api";
import { useMutation } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useState } from "react";

const goals = ["Pass exams", "Learn programming", "Prepare interviews", "Build projects", "Debug assignments"];
export default function OnboardingPage() {
  const router = useRouter(); const [experience, setExperience] = useState("BEGINNER"); const [preferredLang, setLanguage] = useState("JavaScript"); const [learningGoals, setGoals] = useState<string[]>(["Learn programming"]); const [teachingStyle, setStyle] = useState("INTERACTIVE_QUESTIONING");
  const save = useMutation({ mutationFn: async () => api.post("/user/onboarding", { experience, preferredLang, learningGoals, teachingStyle }), onSuccess: () => router.replace("/dashboard") });
  const toggleGoal = (goal: string) => setGoals(current => current.includes(goal) ? current.filter(x => x !== goal) : [...current, goal]);
  return <main className="min-h-screen flex items-center justify-center p-6"><form onSubmit={e => { e.preventDefault(); save.mutate(); }} className="w-full max-w-xl p-7 rounded-2xl bg-card border border-border/50 space-y-6"><div><p className="text-primary text-sm">Welcome to Conrad</p><h1 className="text-3xl font-bold mt-1">Personalize your mentor</h1><p className="text-sm text-muted-foreground mt-2">These choices shape the guidance Conrad gives you.</p></div><label className="block">Experience<select value={experience} onChange={e => setExperience(e.target.value)} className="mt-2 p-3 w-full rounded bg-muted"><option value="COMPLETE_BEGINNER">Complete beginner</option><option value="BEGINNER">Beginner</option><option value="INTERMEDIATE">Intermediate</option><option value="ADVANCED">Advanced</option></select></label><label className="block">Primary language<input value={preferredLang} onChange={e => setLanguage(e.target.value)} className="mt-2 p-3 w-full rounded bg-muted" /></label><fieldset><legend>Learning goals</legend><div className="flex flex-wrap gap-2 mt-2">{goals.map(goal => <button type="button" onClick={() => toggleGoal(goal)} key={goal} className={`px-3 py-2 rounded-full text-sm ${learningGoals.includes(goal) ? "bg-primary text-primary-foreground" : "bg-muted"}`}>{goal}</button>)}</div></fieldset><label className="block">Teaching style<select value={teachingStyle} onChange={e => setStyle(e.target.value)} className="mt-2 p-3 w-full rounded bg-muted"><option value="MORE_HINTS">More hints</option><option value="DETAILED_EXPLANATIONS">Detailed explanations</option><option value="INTERACTIVE_QUESTIONING">Interactive questioning</option><option value="FAST_LEARNING">Fast learning</option></select></label><button disabled={save.isPending || !learningGoals.length} className="w-full p-3 bg-primary text-primary-foreground rounded font-semibold">{save.isPending ? "Saving…" : "Start learning"}</button>{save.isError && <p className="text-sm text-destructive">Unable to save your preferences. Please try again.</p>}</form></main>;
}
